const UserAnswerTypes = {
    ADD_USER_ANSWER: 'ADD_USER_ANSWER',
    SUBMIT_USER_ANSWER_START: 'SUBMIT_USER_ANSWER_START',
    SUBMIT_USER_ANSWER_SUCCESS: 'SUBMIT_USER_ANSWER_SUCCESS',
    SUBMIT_USER_ANSWER_FAILURE: 'SUBMIT_USER_ANSWER_FAILURE',

    GET_RESULT: 'GET_RESULT'
}

export default UserAnswerTypes;